# Generated by Django 3.2.7 on 2021-09-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('appointment', models.BooleanField()),
                ('walkin', models.BooleanField()),
                ('hours', models.CharField(max_length=100)),
            ],
        ),
    ]
